services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: next-loop
      MYSQL_USER: next-loop
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
   mariadb_network:
    name: mariadb_network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local

# maria111
